[package]
name = "x64_ps2_mouse"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
ps2-mouse = { git = "https://github.com/NathanMcMillan54/ps2-mouse" }
printk = { path = "../../../../kernel/printk/" }
spinning_top = "0.2.4"
x86_64 = "0.13.6"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
