[package]
name = "nkuefi"
version = "0.1.0"
edition = "2018"
description = "UEFI boot and setup for Novusk Aarch64 and x86"

[dependencies]
kernel = { path = "../../kernel/" }
uefi = "0.8.1"
uefi-services = "0.5.1"
