[package]
name = "x86"
version = "0.1.0"
edition = "2018"
description = "x86 family support for Novusk"

[dependencies]
init = { path = "../../init/" }
libcolor = { path = "../../lib/libcolor/", features = ["uefi_colors", "vga_colors"] }
libefi = { path = "../../lib/libefi/" }
macros = { path = "../../kernel/macros/" }
spin = "0.5.2"
vga = { path = "../../gpu/vga/" }
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
