[package]
name = "userspace"
version = "0.1.0"
authors = ["Nathan McMillan"]
edition = "2018"

[dependencies]
doom_loader = { path = "../../drivers/userspace/doom_loader/" }
libefi = { path = "../../lib/libefi/" }
libnu = "0.1.2"
printk = { path = "../../kernel/printk/" }
