[package]
name = "aarch64"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "aarch64_novusk"
path = "src/lib.rs"
edition = "2018"

[dependencies]
# Dependencies
arm = { path = "../arm/" }
rlibc = "1.0.0"
spin = "0.9.0"
uefi = "0.8.1"
uefi-macros = "0.3.3"
# Drivers
led = { path = "../../drivers/firmware/led/" }
uefi_kd = { path = "../../drivers/uefi_kd/" }
# Include
novusk = { path = "../../include/novusk/" }
# Kernel
kerror = { path = "../../kernel/kerror/" }
kinfo = { path = "../../kernel/kinfo/" }
init = { path = "../../init/" }
printk = { path = "../../kernel/printk/" }
sys = { path = "../../kernel/sys/" }
userspace = { path = "../../kernel/userspace/" }
# Libraries
libn = { path = "../../lib/libn/" }
# Modules
armm = { path = "../../kernel/modules/armm/" }

# Feature
register = { version = "1.x.x", optional = true }

[dependencies.lazy_static]
version = "1"
features = ["spin_no_std"]

[dependencies.uefi-services]
version = "0.5.1"

# Board
[features]
default = []
uefi_rpi3 = ["register"]

android_os = ["register"]
uefi_kernel = ["register"]
