[package]
name = "gop"
version = "0.1.0"
edition = "2018"
description = "Graphics Output Protocall, GPU driver for UEFI kernel"

[dependencies]
kernel = { path = "../../kernel/" }
nkuefi = { path = "../../drivers/nkuefi/" }
uefi = "0.8.1"
